# Generated by Django 4.0.4 on 2022-05-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_task', models.CharField(max_length=100)),
                ('city_searched', models.TextField()),
                ('date_of_site_visit', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Search history',
            },
        ),
    ]
